<?php

declare(strict_types=1);

namespace App\Message;

/**
 * Carries one build request onto the `q.builds` queue, where ssg-worker consumes it.
 * BuildController dispatches it and config/packages/messenger.yaml routes it to the `builds` transport.
 * Property names are snake_case because Messenger's symfony_serializer uses them verbatim as JSON keys, and ssg-worker's BuildJob decodes by the same names.
 * The class has no getters because ObjectNormalizer would turn each getter into an extra JSON key.
 *
 * @param string $build_id Per-build UUID v7 generated by the publish API, for tracing a job across services.
 * @param string $static_site_id Identifies the site across builds; used for the job's folder under JOB_STORAGE_DIR.
 * @param string $slug Names the published site directory under PUBLISHED_DIR which translates to the uri path of the published site.
 *                     It is restricted to [A-Za-z0-9_-]{1,128} and BuildController rejects anything else with a 400.
 *                     Slug uniqueness is not enforced: this service has no store, so two sites sending one slug overwrite each other's published site.
 * @param string $title Site title, shown in the page header. Separate from $slug because the slug allow-list excludes spaces.
 * @param string $content_download_url Download url for the build assets.
 * @param string $callback_status_url Callback url to update the build status.
 * @param string $created_at Timestamp when the job was created by the publish API.
 */
final class BuildJob
{
    public function __construct(
        public readonly string $build_id,
        public readonly string $static_site_id,
        public readonly string $slug,
        public readonly string $title,
        public readonly string $content_download_url,
        public readonly string $callback_status_url,
        public readonly string $created_at,
    ) {
    }
}
